version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - "5342:5432"  # Mapping host port 5342 to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp:
